### ISSUE TITLE
No update of values ​​and error message in mm-errorLog

### ISSUE THREAD

**Issue by Ondurin** [st3v0rr/MMM-SolarEdge#8]
The values ​​have not been updated cyclically for about a week now.
When the Magic Mirror or Raspberry Pi is restarted, the values ​​are queried once.

The following error text is displayed in the mm error log:

[2024-11-21 12:19:19.642] [ERROR] Whoops! There was an uncaught exception...
[2024-11-21 12:19:19.654] [ERROR] SyntaxError: Unterminated string in JSON at position 321 (line 1 column 322)
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/home/magic/MagicMirror/modules/MMM-SolarEdge/node_helper.js:57:22)
    at IncomingMessage.emit (node:events:519:28)
    at Readable.read (node:internal/streams/readable:780:10)
    at flow (node:internal/streams/readable:1281:53)
    at resume_ (node:internal/streams/readable:1260:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[2024-11-21 12:19:19.655] [ERROR] MagicMirror² will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[2024-11-21 12:19:19.656] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MagicMirrorOrg/MagicMirror/issues
[2024-11-21 12:19:19.659] [ERROR] Whoops! There was an uncaught exception...
[2024-11-21 12:19:19.660] [ERROR] SyntaxError: Unexpected token 'L', "Level":13,"... is not valid JSON
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/home/magic/MagicMirror/modules/MMM-SolarEdge/node_helper.js:57:22)
    at IncomingMessage.emit (node:events:519:28)
    at Readable.read (node:internal/streams/readable:780:10)
    at flow (node:internal/streams/readable:1281:53)
    at emitReadable_ (node:internal/streams/readable:845:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
[2024-11-21 12:19:19.665] [ERROR] MagicMirror² will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[2024-11-21 12:19:19.666] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MagicMirrorOrg/MagicMirror/issues

**Comment by Ondurin** [comment]
The problem has resolved itself. The data is displayed and updated correctly.
